sonar.projectKey=HasnainWorks_hasnain-mern-10pshine
sonar.organization=hasnainworks

sonar.projectName=hasnain-mern-10pshine
sonar.projectVersion=1.0

sonar.sources=.
sonar.exclusions=**/node_modules/**,**/dist/**,**/.git/**,**/coverage/**

sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info

sonar.sourceEncoding=UTF-8